export const sectors = [
  { id: 'intro', label: 'MISSION CONTROL', sector: 'DEEP SPACE', state: 'WAKE SEQUENCE' },
  { id: 'about', label: 'ABOUT', sector: 'AEON-01', state: 'PLANETARY ENTRY' },
  { id: 'missions', label: 'WORK', sector: 'MISSION BELT', state: 'SEARCH DISCOVERY' },
  { id: 'experience', label: 'EXPERIENCE', sector: 'KEYWORD PLANET', state: 'SYSTEMS ONLINE' },
  { id: 'services', label: 'SERVICES', sector: 'DATA SPINE', state: 'NETWORK LINKED' },
  { id: 'process', label: 'PROCESS', sector: 'ANALYTICS ORBIT', state: 'SOURCE DECODED' },
  { id: 'skills', label: 'SKILLS', sector: 'CONSTELLATION', state: 'NODES LINKED' },
  { id: 'signature', label: 'SIGNATURE', sector: 'GROWTH PLANET', state: 'UNIVERSE REVEALED' },
  { id: 'contact', label: 'CONTACT', sector: 'DOCK-09', state: 'FINAL MISSION' },
  { id: 'complete', label: 'COMPLETE', sector: 'OUTER ORBIT', state: 'MISSION COMPLETE' }
];

export const missions = [{"no": "01", "name": "KNOWLEDGE & ENTITY SEO", "type": "WIKIPEDIA / RESEARCH", "body": "Factual, search-aware knowledge content built around long-tail intent, clean hierarchy and entity clarity.", "challenge": "Explain technical and scientific topics clearly for humans and search systems.", "approach": "Research-first writing, descriptive headings and precise entity relationships.", "result": "40+ published articles across knowledge-led and search-focused topics.", "url": "https://en.wikipedia.org/wiki/Heat_exchanger", "tech": ["Research", "Entity SEO", "Content Writing"]}, {"no": "02", "name": "SEO-FIRST WEB EXPERIENCES", "type": "FRONTEND / TECHNICAL SEO", "body": "Hand-coded pages that connect design, semantic structure and search fundamentals.", "challenge": "Create fast, legible pages without burying search fundamentals.", "approach": "Semantic HTML, heading hierarchy, metadata, canonicals and performance-aware CSS.", "result": "Clean frontend foundations designed for usability and technical SEO review.", "url": "#intro", "tech": ["HTML / CSS", "Technical SEO", "Performance"]}, {"no": "03", "name": "SEARCH CONTENT SYSTEMS", "type": "B2B / B2C / D2C STRATEGY", "body": "Content architecture for manufacturing and specialist markets, built around real buyer intent.", "challenge": "Translate complex products into useful search experiences without losing technical detail.", "approach": "Intent mapping, category hierarchy, supporting guides, internal links and schema.", "result": "A clearer organic growth foundation for businesses with limited search visibility.", "url": "#contact", "tech": ["Intent Research", "Schema", "Content Strategy"]}];
export const skills = [["Technical SEO", "Crawlability, indexation, canonicals and structured data. Tools: Screaming Frog and Search Console."], ["On-Page SEO", "Titles, headings and intent alignment for relevant pages."], ["Local SEO", "Google Business Profile, local intent and location content."], ["Intent Research", "Keyword clusters, competitive gaps and buyer journeys. Tools: Ahrefs and Semrush."], ["Content Strategy", "Connected product, category and informational content."], ["Entity Writing", "Research-led writing with clear topics and relationships."], ["Search Console", "Query segmentation, CTR analysis and search performance diagnostics."], ["GA4", "Understand acquisition, engagement and conversion events."], ["HTML / CSS", "Semantic, accessible and performance-conscious pages."], ["Schema", "Structured data and entity relationships."], ["Core Web Vitals", "PageSpeed Insights and practical page experience improvements."], ["Looker Studio", "Useful reporting that connects observations with next steps."]];
